[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
rust_chain = "FpRALKURtearnyVigz6w1NVGQaHGZPGudR379gEomNfV"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/aura/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
